baseURL: ''
languageCod: 'en-us'
title: 'copan:LPJmL'
theme: "toha"

# Manage languages
# For any more details, you can check the official documentation: https://gohugo.io/content-management/multilingual/
languages:
  en:
    languageName: English
    weight: 1

# Control TOC depth
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false
  highlight:
    style: github
    lineNos: false
    lineNumbersInTable: false
    noClasses: false
    codeFences: true

# At least HTML and JSON are required for the main HTML content and
# client-side JavaScript search
outputs:
  home:
    - HTML
    - RSS
    - JSON

# Enable global emoji support
enableEmoji: true

# Site parameters
params:
  logo:
    main: /images/logo.svg
    inverted: /images/logo.svg
    favicon: /images/logo.svg

  # GitHub repo URL and branch of your site
  gitRepo: https://github.com/pik-copan/copanlpjml
  gitBranch: main

  topNavbar:
    maxVisibleSections: 5

  theme: light
  themeSwitching: false

  # specify whether you want to write some blog posts or not
  enableBlogPost: false
  # specify whether you want to show Table of Contents in reading page
  enableTOC: true
  # specify whether you want the language flags to be displayed.
  showFlags: true

  footer:
    enable: true
    navigation:
      enable: true
      customMenus: true
    contactMe:
      enable: true
    disclaimer:
      enable: false

# Provide newsletter configuration.
# This feature has been implemented for Mailchimp only for now.
# You can also hide it from the footer.
newsletter:
  # specify whether you want to display the newsletter form
  enable: false
