name: Hugo CI with Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  # Trigger when docs are updated
  repository_dispatch:
    types: [docs-updated]

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Test Hugo build (without docs)
        run: |
          echo "Testing Hugo build without external docs..."
          hugo --logLevel info
          
      - name: Verify output
        run: |
          ls -la public/
          echo "✅ Hugo build successful"

  pages:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      pages: write
      id-token: write
      actions: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Download latest documentation
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build-docs-artifact.yml
          repo: pik-copan/pycopanlpjml  # 🔄 UPDATE THIS TO YOUR ACTUAL REPO
          name: pycopanlpjml-docs-latest
          path: ./static/docs
          search_artifacts: true
          check_artifacts: true
          if_no_artifact_found: warn
        continue-on-error: true

      - name: Debug downloaded content
        run: |
          echo "Checking downloaded docs..."
          ls -la static/ || echo "No static directory"
          ls -la static/docs/ || echo "No docs downloaded"

      - name: Build Hugo site
        run: |
          echo "Building Hugo site with documentation..."
          hugo --logLevel info

      - name: Upload public folder as artifact
        uses: actions/upload-artifact@v4
        with:
          name: public-main
          path: public/
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: copanlpjml.pik-potsdam.de
