name: Hugo CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Hugo
        uses: klakegg/hugo-action@v2

      - name: Build Hugo site
        run: hugo

      - name: Upload public folder as artifact
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: public/

    if: github.ref != 'refs/heads/main' # Skip on the 'main' branch

  pages:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Hugo
        uses: klakegg/hugo-action@v2

      - name: Build Hugo site
        run: hugo

      - name: Upload public folder as artifact
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: public/
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
